POST https://mini.infiniter.eu
Content-Type: application/json

{
    "url": "https://jsonplaceholder.typicode.com/todos/1",
    "name": "todos"
}

POST https://mini.infiniter.eu
Content-Type: application/json

{
    "url": "https://google.com"
}

GET https://mini.infiniter.eu/all

GET https://mini.infiniter.eu/todos
GET https://mini.infiniter.eu/c1j9rf
