POST http://localhost:13000
Content-Type: application/json

{
    "url": "https://jsonplaceholder.typicode.com/todos/1",
    "name": "todos"
}

POST http://localhost:13000
Content-Type: application/json

{
    "url": "https://google.com"
}

GET http://localhost:13000/all
GET http://localhost:13000/token/haha

GET http://localhost:13000/todos
GET http://localhost:13000/c1j9rf
